// Curated Solana universe (67 tokens) spanning every cap tier — from $1B
// majors down to $1M fresh launches — plus the Solana infrastructure tokens
// worth indexing.
//
// EVERY mint here was read straight from Jupiter's own token API, never typed
// by hand or recalled from memory: a wrong mint means someone buys the wrong
// token with real money. Candidates additionally had to clear a quality bar —
// live price, >=$150k liquidity, >=800 holders, >=$800k mcap and an organic
// score >=25 — so nothing in the curated list is a ghost or pure bot volume.
// Stablecoins, wrapped assets, LSTs and tokenized equities are excluded by
// design; two very fresh launches were dropped for being unverifiable.
// Provenance is labelled, never assumed: pump.fun's API also indexes external
// tokens, so appearing there is not proof of launching there.
// Icons served from DexScreener's token-image CDN (reliable host).
export type CuratedToken = {
  mint: string;
  symbol: string;
  name: string;
  icon: string | null;
  decimals: number;
  coingeckoId: string | null;
  genres: string[];
  launchedAt: number | null; // pump.fun created_timestamp (ms)
};

export const GENRE_INFO: { name: string; description: string; source: string }[] = [
  { name: "AI Agents", description: "AI-born or AI-run tokens — Truth Terminal spawns, agent frameworks, autonomous creators.", source: "https://www.coingecko.com/en/categories/ai-meme-coins" },
  { name: "Dogs", description: "Dog-themed pump launches carrying the founding meme lineage.", source: "https://www.coingecko.com/en/categories/dog-themed-coins" },
  { name: "Zoo", description: "Real viral animals turned tickers — the pygmy hippo and the squirrel.", source: "https://www.coingecko.com/learn/what-is-moodeng-crypto-hippo-memecoin-solana" },
  { name: "Chan Culture", description: "Sigma memes, doomers and financial nihilism from chan culture.", source: "https://iq.wiki/wiki/spx6900-spx" },
  { name: "TikTok Viral", description: "TikTok and Gen-Z viral formats with mainstream reach.", source: "https://coinedition.com/meme-coin-promotion-shifts-to-tiktok-as-chillguy-goes-viral/" },
  { name: "Celebrity & IP", description: "Real people, artworks and brands — from Ansem's bull to the duct-taped banana.", source: "https://www.chaincatcher.com/en/article/2159892" },
  { name: "Parody", description: "Self-aware satire of crypto and TradFi itself.", source: "https://en.cryptonomist.ch/2025/03/04/spx6900-the-token-of-the-memecoin-that-parodies-the-sp500/" },
  { name: "2024 Class", description: "The pump.fun breakout class of 2024 — the era that built the launchpad.", source: "https://en.wikipedia.org/wiki/Pump.fun" },
  { name: "2025 Class", description: "2025 graduates that survived the launchpad flood.", source: "https://en.wikipedia.org/wiki/Pump.fun" },
  { name: "Fresh 2026", description: "This cycle's breakouts — young, liquid, fast-rotating.", source: "https://www.coingecko.com/en/coins/the-black-bull" },
  { name: "Majors", description: "The memecoins everyone already knows — deepest liquidity, lowest slippage.", source: "https://www.coingecko.com/en/categories/meme-token" },
  { name: "Solana Core", description: "The infrastructure the trenches actually run on — launchpads, routers, DePIN.", source: "https://solana.com/ecosystem" },
  { name: "DeFi", description: "Routers, perps and money markets rather than memes.", source: "https://defillama.com/chain/Solana" },
  { name: "DePIN", description: "Decentralised physical infrastructure — compute, connectivity, mapping.", source: "https://www.coingecko.com/en/categories/depin" },
  { name: "Political", description: "Election-cycle and political-figure tokens.", source: "https://www.coingecko.com/en/categories/politifi" },
  { name: "Cats", description: "Cat-themed launches — the eternal answer to the dogs.", source: "https://www.coingecko.com/en/categories/cat-themed-coins" },
  { name: "Brainrot", description: "Italian-brainrot and TikTok character memes — Tung Tung Sahur and friends.", source: "https://knowyourmeme.com/memes/subcultures/italian-brainrot" },
  { name: "NFT & IP", description: "Tokens attached to real NFT brands and licensed meme IP.", source: "https://www.coingecko.com/en/categories/nft" },
  { name: "Gaming", description: "Game and game-adjacent tokens.", source: "https://www.coingecko.com/en/categories/gaming" },
  { name: "Launchpad", description: "The launchpads themselves and the figures behind them.", source: "https://pump.fun" },
  { name: "2023 Class", description: "Pre-pump.fun survivors that founded Solana meme culture.", source: "https://www.coingecko.com/en/categories/solana-meme-coins" },
];

export const PLAYSTYLES: { name: string; description: string; source: string }[] = [
  { name: "New-Pair Trenching", description: "Trades brand-new launches in their first minutes, riding violent early momentum for fast in-and-out.", source: "https://crypto.news/what-are-the-trenches-solana-memecoin-culture" },
  { name: "Catalyst Plays", description: "Event-driven entries around listings, unlocks, elections, and product launches — in ahead of the date, out on the news.", source: "https://www.kucoin.com/news/articles/crypto-market-braces-for-key-catalysts" },
  { name: "Narrative Frontrunning", description: "Buys an emerging theme before it trends and exits into the crowd once it does.", source: "https://www.sharpe.ai/learn/memecoin-narrative-tracker" },
  { name: "Majors Rotation", description: "Rotates through the large-cap graduates as sector momentum shifts.", source: "https://blockchain.news/flashnews/memecoin-rotation-alert" },
  { name: "Slow Cook", description: "Accumulates the deep-liquidity graduates and holds through cycles instead of scalping.", source: "https://www.mexc.com/en-GB/crypto-pulse/article/memecoin-price-strategies" },
  { name: "Revival Plays", description: "Targets left-for-dead coins showing renewed volume and holder growth, betting on a second pump.", source: "https://www.ccn.com/news/crypto/memecoins-comeback-2026" },
];

export const CURATED_TOKENS: CuratedToken[] = [
  {
    mint: "9BB6NFEcjBCtnNLFko2FqVQBq8HHM13kCyYcdQbgpump",
    symbol: "FARTCOIN",
    name: "Fartcoin",
    icon: "https://dd.dexscreener.com/ds-data/tokens/solana/9BB6NFEcjBCtnNLFko2FqVQBq8HHM13kCyYcdQbgpump.png?size=lg",
    decimals: 6,
    coingeckoId: "fartcoin",
    genres: ["AI Agents","2024 Class"],
    launchedAt: 1729231506539,
  },
  {
    mint: "2qEHjDLDLbuBgRYvsxhc5D6uDWAivNFZGan56P1tpump",
    symbol: "PNUT",
    name: "Peanut the Squirrel",
    icon: "https://dd.dexscreener.com/ds-data/tokens/solana/2qEHjDLDLbuBgRYvsxhc5D6uDWAivNFZGan56P1tpump.png?size=lg",
    decimals: 6,
    coingeckoId: "peanut-the-squirrel",
    genres: ["Zoo","2024 Class"],
    launchedAt: 1730384501286,
  },
  {
    mint: "ED5nyyWEzpPPiWimP8vYm7sD7TD3LAt3Q3gRTWHzPJBY",
    symbol: "MOODENG",
    name: "Moo Deng",
    icon: "https://dd.dexscreener.com/ds-data/tokens/solana/ED5nyyWEzpPPiWimP8vYm7sD7TD3LAt3Q3gRTWHzPJBY.png?size=lg",
    decimals: 6,
    coingeckoId: "moo-deng",
    genres: ["Zoo","TikTok Viral","2024 Class"],
    launchedAt: 1725989128495,
  },
  {
    mint: "63LfDmNb3MQ8mw9MtZ2To9bEA2M71kZUUGq5tiJxcqj9",
    symbol: "GIGA",
    name: "GIGACHAD",
    icon: "https://dd.dexscreener.com/ds-data/tokens/solana/63LfDmNb3MQ8mw9MtZ2To9bEA2M71kZUUGq5tiJxcqj9.png?size=lg",
    decimals: 5,
    coingeckoId: "gigachad-2",
    genres: ["Chan Culture","2024 Class"],
    launchedAt: 1704402888000,
  },
  {
    mint: "CzLSujWBLFsSjncfkh59rUFqvafWcY5tzedWJSuypump",
    symbol: "GOAT",
    name: "Goatseus Maximus",
    icon: "https://dd.dexscreener.com/ds-data/tokens/solana/CzLSujWBLFsSjncfkh59rUFqvafWcY5tzedWJSuypump.png?size=lg",
    decimals: 6,
    coingeckoId: "goatseus-maximus",
    genres: ["AI Agents","Chan Culture","2024 Class"],
    launchedAt: 1728594508154,
  },
  {
    mint: "Df6yfrKC8kZE3KNkrHERKzAetSxbrWeniQfyJY4Jpump",
    symbol: "CHILLGUY",
    name: "Just a chill guy",
    icon: "https://dd.dexscreener.com/ds-data/tokens/solana/Df6yfrKC8kZE3KNkrHERKzAetSxbrWeniQfyJY4Jpump.png?size=lg",
    decimals: 6,
    coingeckoId: "chill-guy",
    genres: ["Dogs","TikTok Viral","2024 Class"],
    launchedAt: 1728174673742,
  },
  {
    mint: "GJAFwWjJ3vnTsrQVabjBVK2TYB1YtRCQXRDfDgUnpump",
    symbol: "ACT",
    name: "Act I : The AI Prophecy",
    icon: "https://dd.dexscreener.com/ds-data/tokens/solana/GJAFwWjJ3vnTsrQVabjBVK2TYB1YtRCQXRDfDgUnpump.png?size=lg",
    decimals: 6,
    coingeckoId: "act-i-the-ai-prophecy",
    genres: ["AI Agents","2024 Class"],
    launchedAt: 1729337230871,
  },
  {
    mint: "9cRCn9rGT8V2imeM2BaKs13yhMEais3ruM3rPvTGpump",
    symbol: "ANSEM",
    name: "The Black Bull",
    icon: "https://dd.dexscreener.com/ds-data/tokens/solana/9cRCn9rGT8V2imeM2BaKs13yhMEais3ruM3rPvTGpump.png?size=lg",
    decimals: 6,
    coingeckoId: "the-black-bull",
    genres: ["Celebrity & IP","Fresh 2026"],
    launchedAt: 1781643948000,
  },
  {
    mint: "9PR7nCP9DpcUotnDPVLUBUZKu5WAYkwrCUx9wDnSpump",
    symbol: "BAN",
    name: "Comedian",
    icon: "https://dd.dexscreener.com/ds-data/tokens/solana/9PR7nCP9DpcUotnDPVLUBUZKu5WAYkwrCUx9wDnSpump.png?size=lg",
    decimals: 6,
    coingeckoId: "comedian",
    genres: ["Celebrity & IP","2024 Class"],
    launchedAt: 1729865058694,
  },
  {
    mint: "Ce2gx9KGXJ6C9Mp5b5x1sn9Mg87JwEbrQby4Zqo3pump",
    symbol: "NEET",
    name: "NotInEmploymentEducationTraining",
    icon: "https://dd.dexscreener.com/ds-data/tokens/solana/Ce2gx9KGXJ6C9Mp5b5x1sn9Mg87JwEbrQby4Zqo3pump.png?size=lg",
    decimals: 6,
    coingeckoId: "neet",
    genres: ["Chan Culture","2025 Class"],
    launchedAt: 1745713920819,
  },
  {
    mint: "Dfh5DzRgSvvCFDoYc2ciTkMrbDfRKybA4SoFbPmApump",
    symbol: "PIPPIN",
    name: "Pippin",
    icon: "https://dd.dexscreener.com/ds-data/tokens/solana/Dfh5DzRgSvvCFDoYc2ciTkMrbDfRKybA4SoFbPmApump.png?size=lg",
    decimals: 6,
    coingeckoId: "pippin",
    genres: ["AI Agents","2024 Class"],
    launchedAt: 1731183096749,
  },
  {
    mint: "DtR4D9FtVoTX2569gaL837ZgrB6wNjj6tkmnX9Rdk9B2",
    symbol: "AURA",
    name: "aura",
    icon: "https://dd.dexscreener.com/ds-data/tokens/solana/DtR4D9FtVoTX2569gaL837ZgrB6wNjj6tkmnX9Rdk9B2.png?size=lg",
    decimals: 6,
    coingeckoId: "aura-on-sol",
    genres: ["TikTok Viral","2024 Class"],
    launchedAt: 1717098849372,
  },
  {
    mint: "y1AZt42vceCmStjW4zetK3VoNarC1VxJ5iDjpiupump",
    symbol: "FARTBOY",
    name: "FARTBOY",
    icon: "https://dd.dexscreener.com/ds-data/tokens/solana/y1AZt42vceCmStjW4zetK3VoNarC1VxJ5iDjpiupump.png?size=lg",
    decimals: 9,
    coingeckoId: "fartboy",
    genres: ["AI Agents","2025 Class"],
    launchedAt: 1736105803000,
  },
  {
    mint: "HgBRWfYxEfvPhtqkaeymCQtHCrKE46qQ43pKe8HCpump",
    symbol: "BERT",
    name: "Bertram The Pomeranian",
    icon: "https://dd.dexscreener.com/ds-data/tokens/solana/HgBRWfYxEfvPhtqkaeymCQtHCrKE46qQ43pKe8HCpump.png?size=lg",
    decimals: 6,
    coingeckoId: "bertram-the-pomeranian",
    genres: ["Dogs","2024 Class"],
    launchedAt: 1727735802382,
  },
  {
    mint: "Cm6fNnMk7NfzStP9CZpsQA2v3jjzbcYGAxdJySmHpump",
    symbol: "BUTTCOIN",
    name: "Buttcoin",
    icon: "https://dd.dexscreener.com/ds-data/tokens/solana/Cm6fNnMk7NfzStP9CZpsQA2v3jjzbcYGAxdJySmHpump.png?size=lg",
    decimals: 6,
    coingeckoId: "buttcoin-7",
    genres: ["Parody","Fresh 2026"],
    launchedAt: 1767964561000,
  },
  {
    mint: "BCdwQBAn8dYB5YjTsoB6TdHAWokxv28k2oZUodERpump",
    symbol: "MANIFEST",
    name: "Manifesting",
    icon: "https://dd.dexscreener.com/ds-data/tokens/solana/BCdwQBAn8dYB5YjTsoB6TdHAWokxv28k2oZUodERpump.png?size=lg",
    decimals: 6,
    coingeckoId: "manifesting",
    genres: ["Fresh 2026"],
    launchedAt: 1778686350000,
  },
  {
    mint: "eL5fUxj2J4CiQsmW85k5FG9DvuQjjUoBHoQBi2Kpump",
    symbol: "UFD",
    name: "Unicorn Fart Dust",
    icon: "https://dd.dexscreener.com/ds-data/tokens/solana/eL5fUxj2J4CiQsmW85k5FG9DvuQjjUoBHoQBi2Kpump.png?size=lg",
    decimals: 6,
    coingeckoId: "unicorn-fart-dust",
    genres: ["Celebrity & IP","2024 Class"],
    launchedAt: 1734399716200,
  },
  {
    mint: "6AJcP7wuLwmRYLBNbi825wgguaPsWzPBEHcHndpRpump",
    symbol: "VINE",
    name: "Vine Coin",
    icon: "https://dd.dexscreener.com/ds-data/tokens/solana/6AJcP7wuLwmRYLBNbi825wgguaPsWzPBEHcHndpRpump.png?size=lg",
    decimals: 6,
    coingeckoId: "vine",
    genres: ["Celebrity & IP","2025 Class"],
    launchedAt: 1737591433339,
  },
  {
    mint: "61V8vBaqAGMpgDQi4JcAwo1dmBGHsyhzodcPqnEVpump",
    symbol: "ARC",
    name: "AI Rig Complex",
    icon: "https://dd.dexscreener.com/ds-data/tokens/solana/61V8vBaqAGMpgDQi4JcAwo1dmBGHsyhzodcPqnEVpump.png?size=lg",
    decimals: 6,
    coingeckoId: "ai-rig-complex",
    genres: ["AI Agents","2024 Class"],
    launchedAt: 1733864953486,
  },
  {
    mint: "FeR8VBqNRSUD5NtXAj2n3j1dAHkZHfyDktKuLXD4pump",
    symbol: "JELLYJELLY",
    name: "jelly-my-jelly",
    icon: "https://dd.dexscreener.com/ds-data/tokens/solana/FeR8VBqNRSUD5NtXAj2n3j1dAHkZHfyDktKuLXD4pump.png?size=lg",
    decimals: 6,
    coingeckoId: "jelly-my-jelly",
    genres: ["Celebrity & IP","2025 Class"],
    launchedAt: 1738193364571,
  },
  {
    mint: "HmjCoarLh5duURfJ333DwfFiPyTCgFT35pRSAoP8pump",
    symbol: "TOS",
    name: "TokenOS AI",
    icon: "https://dd.dexscreener.com/ds-data/tokens/solana/HmjCoarLh5duURfJ333DwfFiPyTCgFT35pRSAoP8pump.png?size=lg",
    decimals: 6,
    coingeckoId: "tokenos-ai",
    genres: ["2025 Class"],
    launchedAt: 1748051194850,
  },
  {
    mint: "UWUy7J86LUiBv5SjAUZ53LMGhtnqvbQ7QNSSkyupump",
    symbol: "UWU",
    name: "Unicorn",
    icon: "https://dd.dexscreener.com/ds-data/tokens/solana/UWUy7J86LUiBv5SjAUZ53LMGhtnqvbQ7QNSSkyupump.png?size=lg",
    decimals: 6,
    coingeckoId: "unicorn-3-2",
    genres: ["Fresh 2026"],
    launchedAt: 1779473739000,
  },
  {
    mint: "HNg5PYJmtqcmzXrv6S9zP1CDKk5BgDuyFBxbvNApump",
    symbol: "ALCH",
    name: "Alchemist AI",
    icon: "https://dd.dexscreener.com/ds-data/tokens/solana/HNg5PYJmtqcmzXrv6S9zP1CDKk5BgDuyFBxbvNApump.png?size=lg",
    decimals: 6,
    coingeckoId: "alchemist-ai",
    genres: ["AI Agents","2024 Class"],
    launchedAt: 1732730008152,
  },
  {
    mint: "DKu9kykSfbN5LBfFXtNNDPaX35o4Fv6vJ9FKk7pZpump",
    symbol: "AVA",
    name: "Ava AI",
    icon: "https://dd.dexscreener.com/ds-data/tokens/solana/DKu9kykSfbN5LBfFXtNNDPaX35o4Fv6vJ9FKk7pZpump.png?size=lg",
    decimals: 6,
    coingeckoId: "ava-ai",
    genres: ["AI Agents","2024 Class"],
    launchedAt: 1731523297743,
  },
  {
    mint: "9AvytnUKsLxPxFHFqS6VLxaxt5p6BhYNr53SD2Chpump",
    symbol: "67",
    name: "The Official 67 Coin",
    icon: "https://dd.dexscreener.com/ds-data/tokens/solana/9AvytnUKsLxPxFHFqS6VLxaxt5p6BhYNr53SD2Chpump.png?size=lg",
    decimals: 6,
    coingeckoId: null,
    genres: ["Brainrot","TikTok Viral","Fresh 2026"],
    launchedAt: null,
  },
  {
    mint: "pumpCmXqMfrsAkQ5r49WcJnRayYRqmXz6ae8H7H9Dfn",
    symbol: "PUMP",
    name: "Pump",
    icon: "https://dd.dexscreener.com/ds-data/tokens/solana/pumpCmXqMfrsAkQ5r49WcJnRayYRqmXz6ae8H7H9Dfn.png?size=lg",
    decimals: 6,
    coingeckoId: null,
    genres: ["Solana Core","Launchpad"],
    launchedAt: null,
  },
  {
    mint: "JUPyiwrYJFskUPiHa7hkeR8VUtAeFoSYbKedZNsDvCN",
    symbol: "JUP",
    name: "Jupiter",
    icon: "https://dd.dexscreener.com/ds-data/tokens/solana/JUPyiwrYJFskUPiHa7hkeR8VUtAeFoSYbKedZNsDvCN.png?size=lg",
    decimals: 6,
    coingeckoId: null,
    genres: ["Solana Core","DeFi"],
    launchedAt: null,
  },
  {
    mint: "4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R",
    symbol: "RAY",
    name: "Raydium",
    icon: "https://dd.dexscreener.com/ds-data/tokens/solana/4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R.png?size=lg",
    decimals: 6,
    coingeckoId: null,
    genres: ["Solana Core","DeFi"],
    launchedAt: null,
  },
  {
    mint: "rndrizKT3MK1iimdxRdWabcF7Zg7AR5T4nud4EkHBof",
    symbol: "RENDER",
    name: "Render Token",
    icon: "https://dd.dexscreener.com/ds-data/tokens/solana/rndrizKT3MK1iimdxRdWabcF7Zg7AR5T4nud4EkHBof.png?size=lg",
    decimals: 8,
    coingeckoId: null,
    genres: ["Solana Core","AI Agents"],
    launchedAt: null,
  },
  {
    mint: "KMNo3nJsBXfcpJTVhZcXLW7RmTwTt4GVFE7suUBo9sS",
    symbol: "KMNO",
    name: "Kamino",
    icon: "https://dd.dexscreener.com/ds-data/tokens/solana/KMNo3nJsBXfcpJTVhZcXLW7RmTwTt4GVFE7suUBo9sS.png?size=lg",
    decimals: 6,
    coingeckoId: null,
    genres: ["Solana Core","DeFi"],
    launchedAt: null,
  },
  {
    mint: "7JA5eZdCzztSfQbJvS8aVVxMFfd81Rs9VvwnocV1mKHu",
    symbol: "GEOD",
    name: "Geodnet Token",
    icon: "https://dd.dexscreener.com/ds-data/tokens/solana/7JA5eZdCzztSfQbJvS8aVVxMFfd81Rs9VvwnocV1mKHu.png?size=lg",
    decimals: 9,
    coingeckoId: null,
    genres: ["Solana Core","DePIN"],
    launchedAt: null,
  },
  {
    mint: "nosXBVoaCTtYdLvKY6Csb4AC8JCdQKKAaWYtx2ZMoo7",
    symbol: "NOS",
    name: "Nosana",
    icon: "https://dd.dexscreener.com/ds-data/tokens/solana/nosXBVoaCTtYdLvKY6Csb4AC8JCdQKKAaWYtx2ZMoo7.png?size=lg",
    decimals: 6,
    coingeckoId: null,
    genres: ["Solana Core","DePIN"],
    launchedAt: null,
  },
  {
    mint: "METAewgxyPbgwsseH8T16a39CQ5VyVxZi9zXiDPY18m",
    symbol: "MPLX",
    name: "Metaplex Token",
    icon: "https://dd.dexscreener.com/ds-data/tokens/solana/METAewgxyPbgwsseH8T16a39CQ5VyVxZi9zXiDPY18m.png?size=lg",
    decimals: 6,
    coingeckoId: null,
    genres: ["Solana Core"],
    launchedAt: null,
  },
  {
    mint: "oreoU2P8bN6jkk3jbaiVxYnG1dCXcYxwhwyK9jSybcp",
    symbol: "ORE",
    name: "ORE",
    icon: "https://dd.dexscreener.com/ds-data/tokens/solana/oreoU2P8bN6jkk3jbaiVxYnG1dCXcYxwhwyK9jSybcp.png?size=lg",
    decimals: 11,
    coingeckoId: null,
    genres: ["Solana Core","DeFi"],
    launchedAt: null,
  },
  {
    mint: "METvsvVRapdj9cFLzq4Tr43xK4tAjQfwX76z3n6mWQL",
    symbol: "MET",
    name: "Meteora",
    icon: "https://dd.dexscreener.com/ds-data/tokens/solana/METvsvVRapdj9cFLzq4Tr43xK4tAjQfwX76z3n6mWQL.png?size=lg",
    decimals: 6,
    coingeckoId: null,
    genres: ["Solana Core","DeFi"],
    launchedAt: null,
  },
  {
    mint: "DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263",
    symbol: "Bonk",
    name: "Bonk",
    icon: "https://dd.dexscreener.com/ds-data/tokens/solana/DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263.png?size=lg",
    decimals: 5,
    coingeckoId: null,
    genres: ["Dogs","Majors","2023 Class"],
    launchedAt: null,
  },
  {
    mint: "EKpQGSJtjMFqKZ9KQanSqYXRcF8fBopzLHYxdM65zcjm",
    symbol: "$WIF",
    name: "dogwifhat",
    icon: "https://dd.dexscreener.com/ds-data/tokens/solana/EKpQGSJtjMFqKZ9KQanSqYXRcF8fBopzLHYxdM65zcjm.png?size=lg",
    decimals: 6,
    coingeckoId: null,
    genres: ["Dogs","Majors","2023 Class"],
    launchedAt: null,
  },
  {
    mint: "2zMMhcVQEXDtdE6vsFS7S7D5oUodfJHE8vd1gnBouauv",
    symbol: "PENGU",
    name: "Pudgy Penguins",
    icon: "https://dd.dexscreener.com/ds-data/tokens/solana/2zMMhcVQEXDtdE6vsFS7S7D5oUodfJHE8vd1gnBouauv.png?size=lg",
    decimals: 6,
    coingeckoId: null,
    genres: ["Zoo","Majors","NFT & IP"],
    launchedAt: null,
  },
  {
    mint: "ukHH6c7mMyiWCf1b9pnWe25TSpkDDt3H5pQZgZ74J82",
    symbol: "BOME",
    name: "BOOK OF MEME",
    icon: "https://dd.dexscreener.com/ds-data/tokens/solana/ukHH6c7mMyiWCf1b9pnWe25TSpkDDt3H5pQZgZ74J82.png?size=lg",
    decimals: 6,
    coingeckoId: null,
    genres: ["Chan Culture","Majors","2024 Class"],
    launchedAt: null,
  },
  {
    mint: "MEW1gQWJ3nEXg2qgERiKu7FAFj79PHvQVREQUzScPP5",
    symbol: "MEW",
    name: "cat in a dogs world",
    icon: "https://dd.dexscreener.com/ds-data/tokens/solana/MEW1gQWJ3nEXg2qgERiKu7FAFj79PHvQVREQUzScPP5.png?size=lg",
    decimals: 5,
    coingeckoId: null,
    genres: ["Cats","Majors","2024 Class"],
    launchedAt: null,
  },
  {
    mint: "J3NKxxXZcnNiMjKw9hYb2K4LUxgwB6t1FtPtQVsv3KFr",
    symbol: "SPX",
    name: "SPX6900 (Wormhole)",
    icon: "https://dd.dexscreener.com/ds-data/tokens/solana/J3NKxxXZcnNiMjKw9hYb2K4LUxgwB6t1FtPtQVsv3KFr.png?size=lg",
    decimals: 8,
    coingeckoId: null,
    genres: ["Parody","Majors","Chan Culture"],
    launchedAt: null,
  },
  {
    mint: "6p6xgHyF7AeE6TZkSmFsko444wqoP15icUSqi2jfGiPN",
    symbol: "TRUMP",
    name: "OFFICIAL TRUMP",
    icon: "https://dd.dexscreener.com/ds-data/tokens/solana/6p6xgHyF7AeE6TZkSmFsko444wqoP15icUSqi2jfGiPN.png?size=lg",
    decimals: 6,
    coingeckoId: null,
    genres: ["Political","Celebrity & IP","Majors"],
    launchedAt: null,
  },
  {
    mint: "FUAfBo2jgks6gB4Z4LfZkqSZgzNucisEHqnNebaRxM1P",
    symbol: "MELANIA",
    name: "Melania Meme",
    icon: "https://dd.dexscreener.com/ds-data/tokens/solana/FUAfBo2jgks6gB4Z4LfZkqSZgzNucisEHqnNebaRxM1P.png?size=lg",
    decimals: 6,
    coingeckoId: null,
    genres: ["Political","Celebrity & IP"],
    launchedAt: null,
  },
  {
    mint: "5UUH9RTDiSpq6HKS6bp4NdU9PNJpXRXuiw6ShBTBhgH2",
    symbol: "TROLL",
    name: "TROLL",
    icon: "https://dd.dexscreener.com/ds-data/tokens/solana/5UUH9RTDiSpq6HKS6bp4NdU9PNJpXRXuiw6ShBTBhgH2.png?size=lg",
    decimals: 6,
    coingeckoId: null,
    genres: ["Chan Culture","NFT & IP"],
    launchedAt: null,
  },
  {
    mint: "Dz9mQ9NzkBcCsuGPFJ3r1bS4wgqKMHBPiVuniW8Mbonk",
    symbol: "USELESS",
    name: "USELESS COIN",
    icon: "https://dd.dexscreener.com/ds-data/tokens/solana/Dz9mQ9NzkBcCsuGPFJ3r1bS4wgqKMHBPiVuniW8Mbonk.png?size=lg",
    decimals: 6,
    coingeckoId: null,
    genres: ["Parody","Chan Culture","2025 Class"],
    launchedAt: null,
  },
  {
    mint: "CB9dDufT3ZuQXqqSfa1c5kY935TEreyBw9XJXxHKpump",
    symbol: "USDUC",
    name: "unstable coin",
    icon: "https://dd.dexscreener.com/ds-data/tokens/solana/CB9dDufT3ZuQXqqSfa1c5kY935TEreyBw9XJXxHKpump.png?size=lg",
    decimals: 6,
    coingeckoId: null,
    genres: ["Parody","Chan Culture"],
    launchedAt: null,
  },
  {
    mint: "6GmAFSYs4gk3FDao5FzzySQpPZaWsa4rUJHacpMpUNgx",
    symbol: "STONK",
    name: "STONK",
    icon: "https://dd.dexscreener.com/ds-data/tokens/solana/6GmAFSYs4gk3FDao5FzzySQpPZaWsa4rUJHacpMpUNgx.png?size=lg",
    decimals: 9,
    coingeckoId: null,
    genres: ["Launchpad","DeFi","2025 Class"],
    launchedAt: null,
  },
  {
    mint: "Ai66LHZG9MCzg1WKdawwqduVAXpNDUuV8M3uyq5ppump",
    symbol: "CATE",
    name: "Cate",
    icon: "https://dd.dexscreener.com/ds-data/tokens/solana/Ai66LHZG9MCzg1WKdawwqduVAXpNDUuV8M3uyq5ppump.png?size=lg",
    decimals: 6,
    coingeckoId: null,
    genres: ["Cats","Dogs","Fresh 2026"],
    launchedAt: null,
  },
  {
    mint: "9Pfync3ejPC9eHqVzq3nYQJAhyhjqpnB9UsaSfLxpump",
    symbol: "KET",
    name: "KET",
    icon: "https://dd.dexscreener.com/ds-data/tokens/solana/9Pfync3ejPC9eHqVzq3nYQJAhyhjqpnB9UsaSfLxpump.png?size=lg",
    decimals: 6,
    coingeckoId: null,
    genres: ["Cats","Fresh 2026"],
    launchedAt: null,
  },
  {
    mint: "A13oRB9FFaiUjfi6LdCg6p9ka1u8SfGkUFs4SKvPpump",
    symbol: "TOAD",
    name: "The Toad Pepe",
    icon: "https://dd.dexscreener.com/ds-data/tokens/solana/A13oRB9FFaiUjfi6LdCg6p9ka1u8SfGkUFs4SKvPpump.png?size=lg",
    decimals: 6,
    coingeckoId: null,
    genres: ["Chan Culture","Fresh 2026"],
    launchedAt: null,
  },
  {
    mint: "Ge87EtsjwRQbHaqQmKRno69RFTwh9bfSsm99XNxTpump",
    symbol: "Jimothy",
    name: "Jimothy The Raccoon",
    icon: "https://dd.dexscreener.com/ds-data/tokens/solana/Ge87EtsjwRQbHaqQmKRno69RFTwh9bfSsm99XNxTpump.png?size=lg",
    decimals: 6,
    coingeckoId: null,
    genres: ["Zoo","Fresh 2026"],
    launchedAt: null,
  },
  {
    mint: "BTr5SwWSKPBrdUzboi2SVr1QvSjmh1caCYUkxsxLpump",
    symbol: "WOLF",
    name: "Wolf",
    icon: "https://dd.dexscreener.com/ds-data/tokens/solana/BTr5SwWSKPBrdUzboi2SVr1QvSjmh1caCYUkxsxLpump.png?size=lg",
    decimals: 6,
    coingeckoId: null,
    genres: ["Parody","DeFi","2025 Class"],
    launchedAt: null,
  },
  {
    mint: "HBoNJ5v8g71s2boRivrHnfSB5MVPLDHHyVjruPfhGkvL",
    symbol: "PURPE",
    name: "Purple Pepe",
    icon: "https://dd.dexscreener.com/ds-data/tokens/solana/HBoNJ5v8g71s2boRivrHnfSB5MVPLDHHyVjruPfhGkvL.png?size=lg",
    decimals: 1,
    coingeckoId: null,
    genres: ["Chan Culture","2023 Class"],
    launchedAt: null,
  },
  {
    mint: "DvjbEsdca43oQcw2h3HW1CT7N3x5vRcr3QrvTUHnXvgV",
    symbol: "DOOD",
    name: "Doodles",
    icon: "https://dd.dexscreener.com/ds-data/tokens/solana/DvjbEsdca43oQcw2h3HW1CT7N3x5vRcr3QrvTUHnXvgV.png?size=lg",
    decimals: 9,
    coingeckoId: null,
    genres: ["NFT & IP","Fresh 2026"],
    launchedAt: null,
  },
  {
    mint: "CARDSccUMFKoPRZxt5vt3ksUbxEFEcnZ3H2pd3dKxYjp",
    symbol: "CARDS",
    name: "Collector Crypt",
    icon: "https://dd.dexscreener.com/ds-data/tokens/solana/CARDSccUMFKoPRZxt5vt3ksUbxEFEcnZ3H2pd3dKxYjp.png?size=lg",
    decimals: 6,
    coingeckoId: null,
    genres: ["NFT & IP","Gaming"],
    launchedAt: null,
  },
  {
    mint: "6NwarBvDkXhByqVp2Qkq5i9XbtA2B3Bwe8SWGu9vpump",
    symbol: "Cupsey",
    name: "Cupsey",
    icon: "https://dd.dexscreener.com/ds-data/tokens/solana/6NwarBvDkXhByqVp2Qkq5i9XbtA2B3Bwe8SWGu9vpump.png?size=lg",
    decimals: 6,
    coingeckoId: null,
    genres: ["Celebrity & IP","Fresh 2026"],
    launchedAt: null,
  },
  {
    mint: "8XtRWb4uAAJFMP4QQhoYYCWR6XXb7ybcCdiqPwz9s5WS",
    symbol: "ALON",
    name: "alon",
    icon: "https://dd.dexscreener.com/ds-data/tokens/solana/8XtRWb4uAAJFMP4QQhoYYCWR6XXb7ybcCdiqPwz9s5WS.png?size=lg",
    decimals: 6,
    coingeckoId: null,
    genres: ["Celebrity & IP","Launchpad","2024 Class"],
    launchedAt: null,
  },
  {
    mint: "4kjruqGHDsSqkMdFfCjV7Vb62HPFhtXyWc2t6JpQzDnz",
    symbol: "GTA6",
    name: "GTA VI",
    icon: "https://dd.dexscreener.com/ds-data/tokens/solana/4kjruqGHDsSqkMdFfCjV7Vb62HPFhtXyWc2t6JpQzDnz.png?size=lg",
    decimals: 9,
    coingeckoId: null,
    genres: ["Gaming","Fresh 2026"],
    launchedAt: null,
  },
  {
    mint: "J8PSdNP3QewKq2Z1JJJFDMaqF7KcaiJhR7gbr5KZpump",
    symbol: "TripleT",
    name: "Tung Tung Tung Sahur",
    icon: "https://dd.dexscreener.com/ds-data/tokens/solana/J8PSdNP3QewKq2Z1JJJFDMaqF7KcaiJhR7gbr5KZpump.png?size=lg",
    decimals: 6,
    coingeckoId: null,
    genres: ["Brainrot","TikTok Viral","Fresh 2026"],
    launchedAt: null,
  },
  {
    mint: "BcHEaaTCvycPwwsJ9yQTXdHP9X2gCLkznDbZ8VySpump",
    symbol: "Jotchua",
    name: "Jotchua",
    icon: "https://dd.dexscreener.com/ds-data/tokens/solana/BcHEaaTCvycPwwsJ9yQTXdHP9X2gCLkznDbZ8VySpump.png?size=lg",
    decimals: 6,
    coingeckoId: null,
    genres: ["Dogs","Fresh 2026"],
    launchedAt: null,
  },
  {
    mint: "EpXtn6xGoZ4Y45vRjiDUHSCGbBoJD5FaEqZbF98YswH1",
    symbol: "MADE",
    name: "SelfMade by SP3ND",
    icon: "https://dd.dexscreener.com/ds-data/tokens/solana/EpXtn6xGoZ4Y45vRjiDUHSCGbBoJD5FaEqZbF98YswH1.png?size=lg",
    decimals: 6,
    coingeckoId: null,
    genres: ["Fresh 2026"],
    launchedAt: null,
  },
  {
    mint: "9sfCHMLWSVy6MD6zr7pR1gD3qbT7C6K1E3dMf2ZBpump",
    symbol: "LAYOOO",
    name: "LAYOOO",
    icon: "https://dd.dexscreener.com/ds-data/tokens/solana/9sfCHMLWSVy6MD6zr7pR1gD3qbT7C6K1E3dMf2ZBpump.png?size=lg",
    decimals: 6,
    coingeckoId: null,
    genres: ["Brainrot","TikTok Viral","Fresh 2026"],
    launchedAt: null,
  },
  {
    mint: "ApZuxdpzMrbEYTGEzeY9afh5pj9d6qPRJCTgQYiipbKg",
    symbol: "CYBERLEEK",
    name: "CyberLeek",
    icon: "https://dd.dexscreener.com/ds-data/tokens/solana/ApZuxdpzMrbEYTGEzeY9afh5pj9d6qPRJCTgQYiipbKg.png?size=lg",
    decimals: 9,
    coingeckoId: null,
    genres: ["Fresh 2026"],
    launchedAt: null,
  },
  {
    mint: "RmtMAYVTTFv2iK9muMrXEoAnSSsZPPgRPbqZCKwNDYk",
    symbol: "EYE",
    name: "BULLS'S EYE",
    icon: "https://dd.dexscreener.com/ds-data/tokens/solana/RmtMAYVTTFv2iK9muMrXEoAnSSsZPPgRPbqZCKwNDYk.png?size=lg",
    decimals: 6,
    coingeckoId: null,
    genres: ["Fresh 2026"],
    launchedAt: null,
  },
  {
    mint: "GMzuntWYJLpNuCizrSR7ZXggiMdDzTNiEmSNHHunpump",
    symbol: "dreams",
    name: "Daydreams",
    icon: "https://dd.dexscreener.com/ds-data/tokens/solana/GMzuntWYJLpNuCizrSR7ZXggiMdDzTNiEmSNHHunpump.png?size=lg",
    decimals: 6,
    coingeckoId: null,
    genres: ["AI Agents","2025 Class"],
    launchedAt: null,
  },
  {
    mint: "XSTuo1fV7HHMhs4BYiwtrWSLsMCJNrooH2AssWTYZqP",
    symbol: "XST",
    name: "XST",
    icon: "https://dd.dexscreener.com/ds-data/tokens/solana/XSTuo1fV7HHMhs4BYiwtrWSLsMCJNrooH2AssWTYZqP.png?size=lg",
    decimals: 6,
    coingeckoId: null,
    genres: ["Fresh 2026"],
    launchedAt: null,
  },
  {
    mint: "PAYmo6moDF3Ro3X6bU2jwe2UdBnBhv8YjLgL1j4DxGu",
    symbol: "PAYAI",
    name: "PayAI",
    icon: "https://dd.dexscreener.com/ds-data/tokens/solana/PAYmo6moDF3Ro3X6bU2jwe2UdBnBhv8YjLgL1j4DxGu.png?size=lg",
    decimals: 9,
    coingeckoId: null,
    genres: ["AI Agents","Fresh 2026"],
    launchedAt: null,
  },
];

export const TOKENS_BY_MINT: Record<string, CuratedToken> = Object.fromEntries(
  CURATED_TOKENS.map((t) => [t.mint, t])
);

export function isCurated(mint: string): boolean {
  return mint in TOKENS_BY_MINT;
}
